/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Text,
  'status' : BookingStatus,
  'endTime' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'slotIndex' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createBooking' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text })],
      [],
    ),
  'getAvailableSlots' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
  'getBookings' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Text,
    'status' : BookingStatus,
    'endTime' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'slotIndex' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createBooking' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text })],
        [],
      ),
    'getAvailableSlots' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
    'getBookings' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };