/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'startTime' : string,
  'status' : BookingStatus,
  'endTime' : string,
  'date' : string,
  'createdAt' : bigint,
  'slotIndex' : bigint,
}
export type BookingStatus = { 'active' : null } |
  { 'cancelled' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'createBooking' : ActorMethod<
    [string, bigint],
    { 'ok' : Booking } |
      { 'err' : string }
  >,
  'getAvailableSlots' : ActorMethod<[string], Array<bigint>>,
  'getBookings' : ActorMethod<[string, string], Array<Booking>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];